- hosts: all
  gather_facts: no
  remote_user: rock64
  become: yes
  tasks:
  - name: "editline"
    lineinfile:
     dest: /etc/systemd/timesyncd.conf
     #line: 'tmpfs   /ramdisk tmpfs   nodev,nosuid,noexec,nodiratime,size=400M   0 0'
     #line: '//192.168.1.10/share2 /storage cifs credentials=/home/odroid/.smbpasswd,iocharset=utf8,sec=ntlm,uid=odroid  0  0'		
     #line: '10.0.0.5:/volume1/homes/    /mnt    nfs     intr,nfsvers=3,rsize=8192,wsize=8192       0       0'
     line: 'NTP=ntp1.unsw.edu.au'
  - name: "restart"
    shell: "systemctl restart systemd-timesyncd"
  - name: 'ntp.conf'
    lineinfile:
     dest: /etc/ntp.conf
     line: 'server ntp1.unsw.edu.au'
  - name: "restart"
    shell: "service ntp restart"
